#!/usr/bin/env python
# cb-wmhacks:
# A script for adding hot corners and aero style window snapping
# to Openbox. Written for CrunchBang Linux <http://crunchbang.org/>
# by Philip Newborough <corenominal@corenominal.org>
# ----------------------------------------------------------------------
# License:
#            DO WHAT THE FUCK YOU WANT TO PUBLIC LICENSE
#                    Version 2, December 2004
#
# Copyright (C) 2004 Sam Hocevar <sam@hocevar.net>
#
# Everyone is permitted to copy and distribute verbatim or modified
# copies of this license document, and changing it is allowed as long
# as the name is changed.
#
#            DO WHAT THE FUCK YOU WANT TO PUBLIC LICENSE
#   TERMS AND CONDITIONS FOR COPYING, DISTRIBUTION AND MODIFICATION
#
#  0. You just DO WHAT THE FUCK YOU WANT TO.
# ----------------------------------------------------------------------

from Xlib import display
from Xlib.ext.xtest import fake_input
from Xlib import X
from subprocess import Popen, PIPE, STDOUT
import sys, time, os, ConfigParser, re

history = '/tmp/cb-wmhacks-'+str(os.getuid())
windows = {}
check_intervall = 0.2

p = Popen(['xdotool','getdisplaygeometry'], stdout=PIPE, stderr=STDOUT)
Dimensions = p.communicate()
Dimensions = Dimensions[0].replace('\n', '')
Dimensions = Dimensions.split(' ')
width = int(Dimensions[0])
height = int(Dimensions[1])
hw = width / 2
rt = width - 1
bt = height - 1
aeroLcommand="wmctrl -r :ACTIVE: -b add,maximized_vert && wmctrl -r :ACTIVE: -b remove,maximized_horz && wmctrl -r :ACTIVE: -e 0,0,0,"+str(hw)+",-1"
aeroRcommand="wmctrl -r :ACTIVE: -b add,maximized_vert && wmctrl -r :ACTIVE: -b remove,maximized_horz && wmctrl -r :ACTIVE: -e 0,"+str(hw)+",0,"+str(hw)+",-1"	


if os.path.exists(history) == False:
	f = open(history,'w')
	f.close()
	
def print_usage():
	print "cb-wmhacks: usage:"
	print "  --help          show this message and exit"
	print "  --kill          attempt to kill any running instances"
	print "  --daemon        run daemon and listen for cursor triggers"
	print "  --aero-left     attempt to snap active window to left of screen"
	print "  --aero-right    attempt to snap active window to right of screen"
	print ""
	exit()

def is_root_window():
	p = Popen(['xdotool', 'getactivewindow'], stdout=PIPE, stderr=STDOUT)
	ID = p.communicate()
	if len(ID[0]) > 50:
		return True

def window_id():
	p = Popen(['xdotool', 'getactivewindow'], stdout=PIPE)
	ID = p.communicate()
	ID = int(ID[0])
	p = Popen(['xdotool', 'getwindowpid', str(ID)], stdout=PIPE)
	PID = p.communicate()
	PID = int(PID[0])
	return str(ID)+'-'+str(PID)

def window_lookup():
	ID = window_id()
	windows = history_load()
	if windows.has_key(ID):
		return True

def window_geometry(ID):
	ID = ID.split('-')
	p = Popen(['xdotool', 'getwindowgeometry', ID[0]], stdout=PIPE)
	p = p.communicate()
	Pos = re.search(r'\d+,\d+', p[0])
	Size = re.search(r'\d+x\d+', p[0])
	if Pos and Size:
		Pos = Pos.group().split(',')
		Size = Size.group().split('x')
		return Pos[0]+'|'+Pos[1]+'|'+Size[0]+'|'+Size[1]

def window_store():
	ID = window_id()
	windows[ID] = window_geometry(ID)
	s = ID +'|'+window_geometry(ID)+'\n'
	f = open(history,'a')
	f.write(s)
	f.close()

def window_restore(D,width):
	ID = window_id()
	G = windows[ID].split('|')
	command = 'wmctrl -r :ACTIVE: -b remove,maximized_vert && '
	#FIXME: adjust horizontal placement, not sure where this discrepancy comes from?
	AdjustT = int(G[1]) - 40
	if D == "L":
		command += 'wmctrl -r :ACTIVE: -e 0,10,'+str(AdjustT)+','+G[2]+','+G[3]
	elif D == "R":
		AdjustR = int(width) - int(G[2]) - 10
		command += 'wmctrl -r :ACTIVE: -e 0,'+str(AdjustR)+','+str(AdjustT)+','+G[2]+','+G[3]
	else:
		command += 'wmctrl -r :ACTIVE: -e 0,'+G[0]+','+str(AdjustT)+','+G[2]+','+G[3]
	del windows[ID]
	if len(windows) == 0:
		o = ''
	else:
		for key in windows:
			h = windows[key].split('|')
			o = key+'|'+h[0]+'|'+h[1]+'|'+h[2]+'|'+h[3]+'\n'
	f = open(history,'w')
	f.write(o)
	f.close()
	os.system(command)

def history_load():
	f = open(history,'r')
	i = 0
	for line in f:
		h = line.split('|')
		h[4] = h[4].replace('\n', '')
		windows[h[0]] = h[1]+'|'+h[2]+'|'+h[3]+'|'+h[4]
	f.close()
	return windows

if len(sys.argv) < 2 or sys.argv[1] == "--help":
	print_usage()

elif sys.argv[1] == "--kill":
	print "Attempting to kill any running instances..."
	os.system('pkill -9 -f cb-wmhacks')
	exit()

elif sys.argv[1] == "--aero-left":
	if is_root_window != True:
		if window_lookup():
			window_restore('K',width)
		else:
			window_store()
			os.system(aeroLcommand)

elif sys.argv[1] == "--aero-right":
	if is_root_window != True:
		if window_lookup():
			window_restore('K',width)
		else:
			window_store()
			os.system(aeroRcommand)


elif sys.argv[1] == "--daemon":
	Config = ConfigParser.ConfigParser()
	cfgdir = os.getenv("HOME")+"/.config/cb-wmhacks"
	rcfile = cfgdir+"/cb-wmhacksrc"
	bounce = 40
	disp = display.Display()
	root=display.Display().screen().root

	def mousepos():
		data = root.query_pointer()._data
		return data["root_x"], data["root_y"], data["mask"]

	def mousemove(x, y):
		fake_input(disp, X.MotionNotify, x=x, y=y)
		disp.sync()

	try:
		cfgfile = open(rcfile)
	except IOError as e:
		if not os.path.exists(cfgdir):
			os.makedirs(cfgdir)
		cfgfile = open(rcfile,'w')
		Config.add_section('Hot Corners')
		Config.set('Hot Corners','top_left_corner_command', 'gmrun')
		Config.set('Hot Corners','top_right_corner_command', '')
		Config.set('Hot Corners','bottom_left_corner_command', '')
		Config.set('Hot Corners','bottom_right_corner_command', '')
		Config.add_section('Aeroesque Hot Snapping')
		Config.set('Aeroesque Hot Snapping','enabled', 'true')
		Config.write(cfgfile)
		cfgfile.close()

	while True:
		Config.read(rcfile)
		time.sleep(check_intervall)
		pos = mousepos()
		aeroesque=Config.get('Aeroesque Hot Snapping','enabled')
		
		if pos[0] <= 2 and pos[1] != 0 and pos[1] != bt and pos[2] == 256 and aeroesque == 'true':
			while pos[2] == 256:
				time.sleep(check_intervall)
				pos = mousepos()
			else:
				pos = mousepos()
				if is_root_window() != True:
					if pos[0] <= 2 and pos[1] != 0 and pos[1] != bt:
						if window_lookup():
							window_restore('L', width)
						else:
							window_store()
							os.system(aeroLcommand)
							mousemove(pos[0] + bounce, pos[1])
		
		elif pos[0] >= rt - 2 and pos[1] != 0 and pos[1] != bt and pos[2] == 256 and aeroesque == 'true':
			while pos[2] == 256:
				time.sleep(check_intervall)
				pos = mousepos()
			else:
				pos = mousepos()
				if is_root_window() != True:
					if pos[0] >= rt - 2 and pos[1] != 0 and pos[1] != bt:
						if window_lookup():
							window_restore('R', width)
						else:
							window_store()
							os.system(aeroRcommand)
							mousemove(pos[0] - bounce, pos[1])

		
		elif pos[0] == 0 and pos[1] == 0:	
			if Config.get('Hot Corners','top_left_corner_command') != '':
				time.sleep(0.2)
				pos = mousepos()
				if pos[0] == 0 and pos[1] == 0:
					mousemove(pos[0] + bounce, pos[1] + bounce)
					os.system('(' + Config.get('Hot Corners','top_left_corner_command') + ') &')
					mousemove(pos[0] + bounce, pos[1] + bounce)
					time.sleep(2)
		
		elif pos[0] == rt and pos[1] == 0:
			if Config.get('Hot Corners','top_right_corner_command') != '':
				time.sleep(0.2)
				pos = mousepos()
				if pos[0] == rt and pos[1] == 0 :
					mousemove(pos[0] - bounce, pos[1] + bounce)
					os.system('(' + Config.get('Hot Corners','top_right_corner_command') + ') &')
					mousemove(pos[0] - bounce, pos[1] + bounce)
					time.sleep(2)

		elif pos[0] == 0 and pos[1] == bt:
			if Config.get('Hot Corners','bottom_left_corner_command') != '':
				time.sleep(0.2)
				pos = mousepos()
				if pos[0] == 0 and pos[1] == bt:
					mousemove(pos[0] + bounce, pos[1] - bounce)
					os.system('(' + Config.get('Hot Corners','bottom_left_corner_command') + ') &')
					mousemove(pos[0] + bounce, pos[1] - bounce)
					time.sleep(2)

		elif pos[0] == rt and pos[1] == bt:
			if Config.get('Hot Corners','bottom_right_corner_command') != '':
				time.sleep(0.2)
				pos = mousepos()
				if pos[0] == rt and pos[1] == bt:
					mousemove(pos[0] - bounce, pos[1] - bounce)
					os.system('(' + Config.get('Hot Corners','bottom_right_corner_command') + ') &')
					mousemove(pos[0] - bounce, pos[1] - bounce)
					time.sleep(2)

else:
	print_usage()
